name: CI Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: make
      run: make -j8
    - name: make test
      run: make test -j8
    - name: run test
      run: | 
        cd bin
        ./coretest
        llvm-profdata merge -o coretest.profdata default.profraw
        llvm-cov show coretest --show-branches=count -instr-profile=coretest.profdata > coretest.cov
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }} # Put the name of your token here
        with:
          args: >
            --define sonar.cfamily.llvm-cov.reportPath=bin/coretest.cov
    - name: clean
      run: make clean
