name: CI macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: make
      run: make -j8
    - name: make test
      run: make test -j8
    - name: run test
      run: ./bin/coretest
    - name: clean
      run: make clean
