name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate Documentation
        run: doxygen doc/doxygen.cfg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./doc/html
